server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:shop}?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:matim198}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: robert.miedzic@gmail.com
    password: dtpffgmpkygbwkwb
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocole: smtp

#   enabled: false
file:
  product: D:\Programowanie\pliki
